development:
 adapter: postgresql
 database: isement_dev
 encoding: unicode
 pool: 5
 timeout: 5000
 username: NormalUse
 password: 720800
 host: localhost

 

production:
 adapter: postgresql
 database: isement_production
 encoding: unicode
 pool: 5
 timeout: 5000
 username: NormalUse
 password: 720800

