development:
 adapter: postgresql
 database: isement_dev
 encoding: unicode
 pool: 5
 timeout: 5000
 username: NormalUse
 password:

 test:
 adapter: postgresql
 database: isement_test
 encoding: unicode
 pool: 5
 timeout: 5000
 username: NormalUse
 password:

production:
 adapter: postgresql
 database: isement_production
 encoding: unicode
 pool: 5
 timeout: 5000

